# Generated by Django 6.0.6 on 2026-06-06 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the crop or product (e.g. Maize, Cassava)', max_length=150, unique=True, verbose_name='Crop Name')),
                ('category', models.CharField(help_text='Category of the crop (e.g. Grains, Tubers, Vegetables)', max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique market or trading center name (e.g. Kampala Market)', max_length=200, unique=True, verbose_name='Market Name')),
                ('region_location', models.CharField(help_text='Region or town where the market is located (e.g. Kampala, Gulu)', max_length=100, verbose_name='Region / Location')),
                ('village', models.CharField(blank=True, help_text='Optional village or sub-location within the region', max_length=150, verbose_name='Village / Sub-location')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['region_location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.IntegerField(help_text='Wholesale price (raw numeric). Store in the smallest currency unit if needed.', verbose_name='Wholesale Price')),
                ('retail_price', models.IntegerField(help_text='Retail price (raw numeric). Store in the smallest currency unit if needed.', verbose_name='Retail Price')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the price was observed or scraped', verbose_name='Recorded At')),
                ('crop', models.ForeignKey(help_text='Crop or product for this price record', on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='api.crop', verbose_name='Crop')),
                ('market', models.ForeignKey(help_text='Market where this price was observed', on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='api.market', verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Price Record',
                'verbose_name_plural': 'Price Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['market', 'crop', 'timestamp'], name='api_pricere_market__ac0968_idx')],
            },
        ),
    ]
