# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agentprofile_notification_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]